teleop_twist_joy_node:
  ros__parameters:

    require_enable_button: false
    #enable_button: 2
    #enable_turbo_button: 12

    axis_linear.x: 1
    scale_linear.x: 0.5
    scale_linear_turbo.x: 1.0

    axis_linear.y: 0
    scale_linear.y: 0.5
    scale_linear_turbo.y: 1.0

    axis_angular.yaw: 2
    scale_angular.yaw: 0.5
    scale_angular_turbo.yaw: 1.0


 